#!/bin/bash

# Syllaby Postman Collection Sync Script
# Since Postman CLI is not available via npm, this script provides
# instructions for manual sync via Postman App

echo "🚀 Syllaby Postman Collection Sync Guide"
echo "========================================"
echo ""
echo "Postman CLI is no longer available via npm."
echo "Please use one of these methods to sync:"
echo ""
echo "📤 METHOD 1: Manual Import (Recommended)"
echo "----------------------------------------"
echo "1. Open Postman Desktop App"
echo "2. Click 'Import' button"
echo "3. Drag and drop these files:"
echo "   - syllaby-api-collection.json"
echo "   - syllaby-*-environment.json files"
echo ""
echo "📤 METHOD 2: Via Postman API"
echo "----------------------------"
echo "1. Get your Postman API Key from:"
echo "   https://web.postman.co/settings/me/api-keys"
echo ""
echo "2. Use curl to upload:"
echo "   See: https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a"
echo ""
echo "📤 METHOD 3: Team Workspace"
echo "---------------------------"
echo "1. Create a team workspace in Postman"
echo "2. Share collection link with team"
echo "3. Everyone imports via shared link"
echo ""
echo "🧪 To run tests locally:"
echo "-----------------------"
echo "npm test:local     # Test with local environment"
echo "npm test:dev       # Test with dev environment"
echo "npm test:staging   # Test with staging environment"
echo ""