name: Validate and Test Postman Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Validate JSON files
      run: npm run validate
    
    - name: Run Newman tests (validation only)
      run: |
        # This is a dry run to validate the collection structure
        npx newman run syllaby-api-collection.json \
          -e syllaby-local-environment.json \
          --bail \
          --suppress-exit-code \
          --iteration-count 1 \
          --folder "Authentication" \
          --reporters cli,json \
          --reporter-json-export newman-report.json
      continue-on-error: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman-report.json

  sync-via-api:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Sync Collection to Postman
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |
        # Check if API key is set
        if [ -z "$POSTMAN_API_KEY" ]; then
          echo "⚠️  POSTMAN_API_KEY not set. Skipping sync."
          echo "To enable sync:"
          echo "1. Get API key from: https://web.postman.co/settings/me/api-keys"
          echo "2. Add to GitHub Secrets: Settings → Secrets → Actions → POSTMAN_API_KEY"
          exit 0
        fi
        
        echo "📤 Syncing to Postman via API..."
        
        # Upload collection
        curl --location --request POST 'https://api.postman.com/collections' \
          --header "X-API-Key: $POSTMAN_API_KEY" \
          --header 'Content-Type: application/json' \
          --data-binary '@syllaby-api-collection.json' \
          --fail-with-body || echo "Collection upload failed"
        
        # Upload environments
        for env in syllaby-*-environment.json; do
          echo "Uploading $env..."
          curl --location --request POST 'https://api.postman.com/environments' \
            --header "X-API-Key: $POSTMAN_API_KEY" \
            --header 'Content-Type: application/json' \
            --data-binary "@$env" \
            --fail-with-body || echo "$env upload failed"
        done